name: Build

on:
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ["16", "18"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install and Build
        run: |
          npm ci
          npm run build

      - name: Error handling
        if: failure()
        run: echo "Build failed!"
